import { TutorialLineChart, TutorialBarChart } from "./charts";
import {
  VectorDiagram,
  VectorAdditionDiagram,
  DotProductDiagram,
  NormalizationDiagram,
  MatrixDiagram,
  MatrixMultiplicationDiagram,
  MatrixVectorDiagram,
  BatchMatrixDiagram,
  TangentLineDiagram,
  GradientDiagram,
  GradientDescentDiagram,
  ChainRuleDiagram,
  ComputationGraphDiagram,
  BackpropDiagram,
  MSELossDiagram,
  CrossEntropyDiagram,
} from "./diagrams";

export const mdxComponents = {
  TutorialLineChart,
  TutorialBarChart,
  VectorDiagram,
  VectorAdditionDiagram,
  DotProductDiagram,
  NormalizationDiagram,
  MatrixDiagram,
  MatrixMultiplicationDiagram,
  MatrixVectorDiagram,
  BatchMatrixDiagram,
  TangentLineDiagram,
  GradientDiagram,
  GradientDescentDiagram,
  ChainRuleDiagram,
  ComputationGraphDiagram,
  BackpropDiagram,
  MSELossDiagram,
  CrossEntropyDiagram,
};
